 List<String> keywords = [
  'greetings',
  'good morning',
  'who are you',
  'bisa',
  'fuck',
  'sorry',
  'hey',
  'give me a minute',
  'no',
  'let me think',
  'lemme think',
  'tell a joke',
  'where are you',
  'the weather',
  'you dance',
  'how old are you',
  'your role',
  'can you sing',
  'to a doctor'
];

 List<String> responses = [
  'Greetings! How can I be of service?',
  'Good morning! How can I be of service?',
  'I am a bot created by bisa Technologies to assist with your health related.How can I be of service?',
  'Bisa is a Tech company which provides IT solutions by creating top quality yet affordable, advanced software, specifically designed to meet the unique needs of its clients. The company is committed to building and developing technological solutions that ensure the continued competitiveness of businesses. Oasis Websoft also strives to keep the character of its software such that its ability to transform is clearly evidenced by persistent growth in every aspect of business.I am a bot created by bisa Technologies to assist with your health related.How can I be of service?',
  'No Comments.',
  'No worries.How else can I assist you?',
  'hey, how are you today?',
  'Sure, I\'m always availabe here :)',
  'Understood. is there anything else you would like to share? if not you can tap the top chat icon to speak to a doctor',
  'Sure, I\'m always availabe here :) ',
  'Sure, I\'m always availabe here :)',
  'Why did the scarecrow win an award? Because he was outstanding in his field.',
  'I exist in the virtual realm',
  'I can\'t provide real-time weather updates',
  'I can\'t dance, but I can help you with your health related issues :)',
  'I don\'t have an age, I\'m just a program. :)',
  'I\'m here to assist you in matters concerning your health. Do you have any health related issues?',
  'I can\'t sing, but I can help you with your health related issues :)',
  'You can tap the top chat icon to speak to a doctor.'
];